---

- hosts: ote_core

  tasks:
    - name: Change the hostname to our standard
      hostname:
        name="{{ ote_core }}"
      when:
        ansible_fqdn != ansible_ssh_host

    - name: restart machine
      command: shutdown -r now "Ansible updates triggered"
      async: 0
      poll: 0
      ignore_errors: True
      when:
        reboot is defined

    - name: Waiting for server to come back up
      local_action: wait_for host="{{ ote_core }}" port=22 state=started

    - name: Fix /etc/hosts removing the old hostname
      tags:
        - hosts
      lineinfile:
        state=present
        dest=/etc/hosts
        line="{{ ansible_default_ipv4.address }} {{ ote_core }} {{ ansible_hostname }}"
        regexp="^{{ ansible_default_ipv4.address }}"
      when:
        ansible_fqdn != ote_core

    - name: Validate ansible_fqdn == ote_core
      tags:
        - validate
      assert:
        that:
          ansible_fqdn == ote_core
